set_property SRC_FILE_INFO {cfile:{C:/Users/dirkt/Documents/School/Project Lab 1/project-lab-1/code/Vivaldo Projects/BAYSYS3_Program/BAYSYS3_Program.srcs/constrs_1/new/basys3_master.xdc} rfile:../../../BAYSYS3_Program.srcs/constrs_1/new/basys3_master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {SW0}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {SW1}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {LED0}]
